defaults:
  - _self_
  - dataloader: dataloader
  - model: egg_model           
#  - exp_defaults: ${dataloader}

trainer:
  cuda_number: '0'
  gpus: 1
  is_logger_enabled: true
  check_val_every_n_epoch: 30
  log_every_n_steps: 25         
  make_checkpoint: True
  checkpoint_path: {}
  

# Projects name
# imput_baseline - where the runs of imputation baseline
# optimization - where the runs of different opimizers to find the one which converges
wadb:
  logger_project_name: new_data_pipeline #imput_baseline #imput_baseline #optimization
  logger_name: clean_check
  entity: edge_generation
  


seed_everything: 42



